site_name: "Computer Science Notes"
site_url:  "https://oisinjohnston.github.io/computer-science-notes/"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format


