site_name: "Computer Science Notes"
site_url:  "https://oisinjohnston.github.io/computer-science-notes/"

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8

